apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "community-solid-server.fullname" . }}
  labels:
    {{- include "community-solid-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "community-solid-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "community-solid-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- $appVersion := .Chart.AppVersion -}}
          {{- with .Values.image }}
          image: "{{.registry}}/{{ .repository }}:{{ .tag | default $appVersion }}"
          {{- end}}
          args: 
            - "-l"
            - "{{ .Values.logLevel}}"
            - "-b"
            - "{{ include "community-solid-server.baseUrl" . }}"
            {{- if .Values.showStacktrace }}
            - "-t"
            {{- end }}
            {{- with .Values.config}}
            - "-c"
            {{- if not .configMapName }}
            - "config/{{.bundled}}.json"
            {{- else }}
            - "/config/{{ .configMapKey }}"
            {{- end }}
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - "-f"
            - "/data/"
            {{- end }}
            {{- range $val := .Values.customParameters }}
            - {{ $val.flag | quote }}
            - {{ $val.value | quote }}
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
          {{- if .Values.config.configMapName }}
            - name: config
              mountPath: /config
          {{- end }}
      volumes:
      {{- if .Values.config.configMapName }}
        - name: config
          configMap:
            name: {{ .Values.config.configMapName }}
            items:
              - key: {{ .Values.config.configMapKey }}
                path: {{ .Values.config.configMapKey }}
      {{- end}}
      {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingClaim . }}
      {{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
      {{- else if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "community-solid-server.fullname" . }}-data
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
