{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "community-solid-server.fullname" . }}-data
  labels:
    {{- include "community-solid-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.persistence.storageClassName }}
    {{- if (eq "-" .Values.persistence.storageClassName) }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
    {{- end }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
