apiVersion: v1
kind: Service
metadata:
  name: {{ include "community-solid-server.fullname" . }}
  labels:
    {{- include "community-solid-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
  selector:
    {{- include "community-solid-server.selectorLabels" . | nindent 4 }}
