apiVersion: v1
entries:
  css:
  - apiVersion: v2
    appVersion: 2.0.1
    created: "2022-01-27T09:48:26.325613985+01:00"
    description: The Community Solid Server is open software that provides you with
      a Solid Pod and identity. This Pod acts as your own personal storage space so
      you can share data with people and Solid applications.
    digest: 52fa8c1cdee625deec144814de9c2a7294a38f75d0668055a8e99136556f5724
    home: https://github.com/idlab-gent/css-helm-chart
    icon: https://raw.githubusercontent.com/solid/community-server/main/templates/images/solid.svg
    keywords:
    - solid
    - pod
    maintainers:
    - email: jasper.vaneessen@ugent.be
      name: jveessen
    name: css
    sources:
    - https://github.com/solid/community-server
    type: application
    urls:
    - css-0.1.0.tgz
    version: 0.1.0
generated: "2022-01-27T09:48:26.324125397+01:00"
