apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "css.fullname" . }}
  labels:
    {{- include "css.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "css.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "css.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "css.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: 
            - "-l"
            - "{{ .Values.logLevel}}"
            - "-b"
            - "{{ include "css.baseUrl" . }}"
            {{- if .Values.showStacktrace }}
            - "-t"
            {{- end }}
            {{- with .Values.config}}
            - "-c"
            {{- if not .configMapName }}
            - "@css:config/{{.bundled}}.json"
            {{- else }}
            - "/config/{{ .configMapKey }}"
            {{- end }}
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - "-f"
            - "/data/"
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /data
          {{- end}}
          {{- if .Values.config.configMapName }}
            - name: config
              mountPath: /config
          {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "css.fullname" . }}-data
      {{- end}}
      {{- if .Values.config.configMapName }}
        - name: config
          configMap:
            name: {{ .Values.config.configMapName }}
            items:
              - key: {{ .Values.config.configMapKey }}
                path: {{ .Values.config.configMapKey }}
      {{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
