name: Check and Update chart README

on: 
  pull_request:
    branches:
      - main
    paths:
      - '*/values.yaml'
  push:
    branches:
      - main
    paths:
      - '*/values.yaml'

jobs:
  check-and-update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v2
        with:
          repository: 'bitnami-labs/readme-generator-for-helm'
          ref: '1af12881436b1f58f0643d733fd5196b4a11caa8'
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install readme-generator-for-helm dependencies
        run: cd readme-generator-for-helm && npm install

      - name: Checkout css-helm-chart
        uses: actions/checkout@v2
        with:
          path: charts

      ## Can be made to check all charts (generic)
      - name: Execute readme-generator-for-helm
        run: readme-generator-for-helm/bin/index.js --values charts/community-solid-server/values.yaml --readme charts/community-solid-server/README.md

      - name: Commit readme
        if: github.ref == 'refs/heads/main'
        run: |
          cd charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add community-solid-server/README.md
          git commit -am "docs: Update chart parameters readme"
          git push

