name: Check README metadata

on: push
    # paths:
    #   - 'community-solid-server/values.yaml'

jobs:
  check-readme-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bitnami-labs/readme-generator-for-helm
        uses: actions/checkout@v2
        with:
          repository: 'bitnami-labs/readme-generator-for-helm'
          ref: '1af12881436b1f58f0643d733fd5196b4a11caa8'
          path: readme-generator-for-helm

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('readme-generator-for-helm/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Install readme-generator-for-helm dependencies
        run: cd readme-generator-for-helm && npm install

      - name: Checkout css-helm-chart
        uses: actions/checkout@v2

      - name: Execute readme-generator-for-helm
        run: |
          ls
          ls readme-generator-for-helm
          ls readme-generator-for-helm/bin
          readme-generator-for-helm/bin/index.js --values community-solid-server/values.yaml --readme community-solid-server/README.md

      # - name: Commit and push changes
      #   run: |
      #     git config --global user.name "readme-generator"
      #     git config --global user.email "jasper.vaneessen@ugent.be"
      #     git add community-solid-server/README.md
      #     git commit -m "Update chart readme according to changes in values.yaml"
      #     git push